version: '2'
services:
    mysql:
        container_name: web-camera-mysql
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: example
            MYSQL_USER: example
            MYSQL_PASSWORD: password
        volumes:
            - ./build/mysql/db:/var/lib/mysql
            - ./build/mysql/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    web:
        container_name: web-camera-nginx
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./build/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www/html/

    php:
        container_name: web-camera-php
        build: ./build/php/
        volumes:
            - .:/var/www/html/
        depends_on:
            - mysql

    redis:
        container_name: web-camera-redis
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./build/redis:/data

    node:
        container_name: web-camera-node
        image: node:latest
        working_dir: /usr/src/app
        tty: true
        volumes:
            - .:/usr/src/app
        ports:
            - 3000:3000
            - 5173:5173

